---
title: "MAX Exchange 分析(R httr)"
author: "kidneyweakx"
date: "2020/10/21"
output: html_document
---
```{r}
rm(list=ls(all=T))
if(!require(pacman)) install.packages("pacman")
pacman::p_load(httr, tidyverse,tidyquant,lubridate)
```
[資料來源API_list](https://max.maicoin.com/documents/api_list)

### 所有市場
```{r}
# summary
r <- GET("https://max-api.maicoin.com/api/v2/summary", add_headers(Accept= "application/json"))
sum <- content(r)
```

### K線
```{r}
market <- 'btctwd';limit <- 1000;
period <- c(1,5,15,30,60,120,240,360,720,1440,4320,10080)
url <- paste('https://max-api.maicoin.com/api/v2/k?market=',
             market,'&limit=',limit,'&period=',period[1], sep='')
r <- GET(url, add_headers(Accept= "application/json"))
k <- content(r)
```

### 處理資料
```{r}
df <- data.frame(matrix(unlist(k), nrow=limit, byrow=T),
                 stringsAsFactors=FALSE)
colnames(df) <- c("timestamp", "open", "high", "low", "close", "volume")
df <- df %>% mutate(timestamp=as_datetime(timestamp)) 
```

### Normal K line
```{r}
# df %>% ggplot(aes(x = timestamp, y = close)) +
#   geom_barchart(aes(open = open, high = high, low = low, close = close)) +
#   labs(title = paste(market, "Line Chart"), y = "Closing Price", x = "") +
#   theme_tq()
df %>% ggplot(aes(x = timestamp, y = close)) +
  geom_candlestick(aes(open = open, high = high,
                       low = low, close = close),
                   color_up = "firebrick3",
                   color_down = "chartreuse3",
                   fill_up  = "firebrick3",
                   fill_down  = "chartreuse3") +
  labs(title = paste(market, "Line Chart"),
       y = "Closing Price", x = "") +
  theme_tq()
```

### K line + MA
```{r}
df %>% ggplot(aes(x = timestamp, y = close)) +
  geom_candlestick(aes(open = open, high = high,
                       low = low, close = close),
                   color_up = "firebrick3",
                   color_down = "chartreuse3",
                   fill_up  = "firebrick3",
                   fill_down  = "chartreuse3") +
  geom_ma(ma_fun = SMA, n = 5, color = "blue", linetype = 7,size = 1) +
  geom_ma(ma_fun = SMA, n = 10, color = "orange", linetype = 7, size = 1) + 
  geom_ma(ma_fun = SMA, n = 20, color = "green", linetype = 7, size = 1) +
  labs(title = paste(market, "Line Chart"),
       y = "Closing Price", x = "") +
  theme_tq()
```


### 繪製均線
```{r}
df <- df %>%
  
  # 計算10日簡單移動平均線參數
  tq_mutate(select = c(close),
            mutate_fun = SMA,
            n = 10) %>%
  rename(ma10 = SMA) %>%
  
  # 計算20日簡單移動平均線參數
  tq_mutate(select = c(close),
            mutate_fun = SMA,
            n = 20) %>%
  rename(ma20 = SMA)

df %>% 
  select(timestamp, close, ma10:ma20) %>% 
  arrange(timestamp) %>% na.omit()
```

### 處理private ZONE
```{r}
rm(list=ls(all=T))
if(!require(pacman)) install.packages("pacman")
pacman::p_load(httr, tidyverse, rjson, base64url, digest,reticulate)
# Sys.getenv("MAX_API_KEY") # Sys.getenv("MAX_API_SECRET")
key = Sys.getenv("MAX_API_KEY")
tmp = Sys.getenv("MAX_API_SECRET")
use_condaenv("cloud",conda = "D:\\app\\Anaconda3\\condabin\\conda")
```

### Python encode
```{python}
# repl_python() # 進入python環境
import base64
import hashlib
import hmac
import json
from time import time as _time
import requests
nonce = int(round(_time() * 1000))
body = {
  'path': f'/api/v2/members/me.json',
  'nonce': nonce,
}
headers = {
  'Accept': 'application/json',
  'User-Agent': 'pyCryptoTrader/1.0.2',
}
bd = json.dumps(body)
payload =  base64.urlsafe_b64encode(json.dumps(body).encode('utf-8')).decode('utf-8')
sign = hmac.new(bytes(r.tmp, 'utf-8'), bytes(payload, 'utf-8'), hashlib.sha256).hexdigest()
headers.update({
  # This header is REQUIRED to send JSON data.
  # or you have to send PLAIN form data instead.
  'Content-Type': 'application/json',
  'X-MAX-ACCESSKEY': r.key,
  'X-MAX-PAYLOAD': payload,
  'X-MAX-SIGNATURE': sign
})
res = requests.get("https://max-api.maicoin.com/api/v2/members/me.json",headers=headers)
# exit
```

### test payload and sign is correct
```{r}
payload <- paste0(base64_urlencode(py$bd),"=")
sign <- hmac(tmp, payload, "sha256")
payload == py$payload; sign == py$sign
body <- data.frame(path='/api/v2/members/me.json', 
                   nonce= py$nonce) %>% rjson::toJSON()
py$bd == body
py$res$content

```

### =============header 製作=================
```{r}
gettime <- function(){
 round( (Sys.time() %>% as.numeric())*1000 )
}
body <- data.frame(path="/api/v2/members/me.json", nonce= gettime()) %>% 
  jsonlite::toJSON() %>% 
  str_replace_all("[\\[\\]]", '')
body <- paste0('{"path": "/api/v2/members/me.json", "nonce":',gettime(),'}')
payload <- paste0(base64_urlencode(body),"=")
sign <- hmac(Sys.getenv("MAX_API_SECRET"), payload, "sha256")
```

### 測試private requests
```{r}
r <- httr::GET("https://max-api.maicoin.com/api/v2/members/me.json",
               body=body,
               add_headers(.headers=c('Accept'= 'application/json',
                                          'User-Agent'= 'pyCryptoTrader/1.0.2',
                                          'Content-Type'= 'application/json',
                                          'X-MAX-ACCESSKEY'= Sys.getenv("MAX_API_KEY"),
                                          'X-MAX-PAYLOAD'= payload,
                                          'X-MAX-SIGNATURE'= sign)))
r$status_code; content(r)
```




