---
title: "MAX Exchange 參照交易所交易"
author: "kidneyweakx"
date: "`r Sys.time()`"
output:
  html_document:
    highlight: pygments
    theme: flatly
    css: ../style.css
---
```{r include=FALSE}
rm(list=ls(all=T));gc()
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse,tidyquant, reticulate, patchwork, scales)
if(!require(binancer)) {
  if(!require(devtools)) install.packages("devtools")
  devtools::install_github("daroczig/binancer")
}
# python anaconda 位置 (修改cloud成你的環境，conda為ana/miniconda路徑)
use_condaenv("cloud",conda = "D:\\app\\Anaconda3\\condabin\\conda") 
max <- import("max.client"); client <- max$Client("","")
```
### 轉換Python list to data.frame()
```{r}
r2df <- function(l){
  data.frame(matrix(unlist(l), nrow=length(l), byrow=T),
                 stringsAsFactors=FALSE)}
```

### get binance and max data
```{r}
# crypto <- c('btc','eth','bch','ltc','xrp')
# yrlong <- 2170
# time <- lubridate::ymd_hms("2019-01-01 00:00:00") - hours(8)
# market <- paste0(toupper(crypto[1],'USDT'))
# limit <- 1000; period <- 1
# bink <- do.call(rbind,lapply(1:yrlong,function(i){
#   start <- time + hours((i-1)*12)
#   end <- time + hours(i*12)-seconds(1)
#   bk <- tryCatch(binance_klines(toupper(market), 
#                   paste0(period,'m'), limit = limit, 
#                   start, end),error=function(e){
#                     data.frame()
#                   })
# }))
# daylong <- yrlong/2
# maxk <- do.call(rbind,lapply(1 :daylong,function(i){
#   start <- as.numeric(time+days((i-1)),tz="UTC")
#   k <- tryCatch(client$get_public_k_line(tolower(market),
#                   toString(1440),
#                   toString(period),
#                   toString(start)) %>%  r2df(),error=function(e){
#                     data.frame()
#                   })
# }))
# 
# colnames(maxk) <- c("date", "open", "high", "low", "close", "volume")
# maxk <- maxk %>% mutate(date=as_datetime(date, tz="Asia/Taipei"))
# save(maxk, bink, file=paste0("2yrk",crypto[1],".RData"))
```

### 讀取五大幣種資料及繪製
```{r}
crypto <- c('btc','eth','bch','ltc','xrp')
sapply(1:length(crypto), function(x){
  load(paste0('2yrk',crypto[x],'.RData'))
  # max 交易所
  max2df <- maxk %>% arrange(date) %>% 
    mutate(ret = log(close) - log(lag(close)),
           thm = strftime(date,"%H:%M:%S")) %>% 
    group_by(thm) %>% 
    mutate(rstd = sd(ret, na.rm=T),
          bdd = mean(rstd),
           ami = abs(mean(ret,na.rm = TRUE))/mean(volume,na.rm = TRUE))
  # 幣安 交易所
  bin2df <- bink %>% arrange(open_time) %>% 
    mutate(ret = log(close) - log(lag(close)),
           thm = strftime(open_time,"%H:%M:%S")) %>% 
    group_by(thm) %>% 
    mutate(rstd = sd(ret, na.rm=T),
           bdd = mean(rstd),
           ami = abs(mean(ret,na.rm = TRUE))/mean(volume,na.rm = TRUE))
  # 取內部計算出的ami、vol及報酬
  mdf <- max2df %>% group_by(thm) %>% 
  summarise(mret = mean(ret, na.rm = T),
            mrstd = mean(rstd, na.rm = T),
            mbdd = mean(bdd, na.rm = T),
            mami = mean(ami, na.rm = T),
            mvol = mean(volume, na.rm = T)) %>% 
  mutate(label = row_number(),exchange="max")
  bdf <- bin2df %>% group_by(thm) %>% 
    summarise(mret = mean(ret, na.rm = T),
              mrstd = mean(rstd, na.rm = T),
              mbdd = mean(bdd, na.rm = T),
              mami = mean(ami, na.rm = T),
              mvol = mean(volume, na.rm = T)) %>% 
    mutate(label = row_number(),exchange="binance")
  mbdf <- rbind(mdf,bdf)
  # 計算價差
  mbv <- mbdf %>% group_by(exchange) %>% 
  summarise(meanvol = mean(mvol, na.rm = T)) %>% 
  spread(key = exchange, meanvol) %>% 
  mutate(v = binance / max)
  cat(crypto[x],"交易量", mbv$v,"倍\n")
  # max + binanace 繪製比較圖
  mbvol <- mbdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>% 
  ggplot(aes(x= dd, y = mvol, col=exchange) ) +
    geom_line() + labs(x= "時間軸", y ="交易量") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mvol == max(bdf$mvol)|mvol==max(mdf$mvol)),
             aes(label = sprintf('%0.2f', mvol)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  mbami <- mbdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>% 
  ggplot(aes(x= dd, y = mami, col=exchange) ) +
    geom_line() + labs(x= "時間軸", y ="Amihud") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mami == max(bdf$mami)|mami==max(mdf$mami)),
             aes(label = sprintf('%0.1f', mami)), hjust = -0.5) + 
    theme(legend.position = "none")
  mbdd <- mbdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>% 
  ggplot(aes(x= dd, y = mrstd, col=exchange) ) +
    geom_line() + labs(x= "時間軸", y ="波動度") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mrstd == max(bdf$mrstd)|mrstd ==max(mdf$mrstd)),
             aes(label = sprintf('%0.1f', mrstd)), hjust = -0.5) + 
    theme(legend.position = "none")
  mbp <- (mbvol|(mbami/mbdd)) +  plot_annotation(
    title = paste('[',crypto[x],']',
                  'binance exchange vs max exchange'))
  print(mbp)
  # max & binanace 分別繪製
  m1 <- mdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
    ggplot(aes(x= dd, y = mvol)) +
    geom_line(col="blue") +
    labs(x= "時間軸", y ="交易量") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mvol==max(mdf$mvol)),
             aes(label = sprintf('%0.2f', mvol)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  m2 <- mdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
    ggplot(aes(x= dd, y = mami)) +
    geom_line(col="blue") +
    labs(x= "時間軸", y ="Amihud") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mami==max(mdf$mami)),
             aes(label = sprintf('%0.2f', mami)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  m3 <- mdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
    ggplot(aes(x= dd, y = mrstd)) +
    geom_line(col="blue") +
    labs(x= "時間軸", y ="波動度") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mrstd==max(mdf$mrstd)),
             aes(label = sprintf('%0.2f', mrstd)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  b1 <- bdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
     ggplot(aes(x= dd, y = mvol)) +
    geom_line(col="orange") +
    labs(x= "時間軸", y ="交易量") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mvol == max(bdf$mvol)),
             aes(label = sprintf('%0.2f', mvol)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  b2 <- bdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
     ggplot(aes(x= dd, y = mami)) +
    geom_line(col="orange") +
    labs(x= "時間軸", y ="Amihud") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mami == max(bdf$mami)),
             aes(label = sprintf('%0.2f', mami)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  b3 <- bdf %>% mutate(dd= ymd_hms(paste("2021-01-01",thm))) %>%
     ggplot(aes(x= dd, y = mrstd)) +
    geom_line(col="orange") +
    labs(x= "時間軸", y ="波動度") + 
       scale_x_datetime(labels = date_format("%H"), 
                        breaks = date_breaks("4 hours"))+
  geom_label(data = . %>% 
               filter(mrstd == max(bdf$mrstd)),
             aes(label = sprintf('%0.2f', mrstd)), hjust = -0.5) +
    theme(legend.position = "bottom",legend.direction = "horizontal")
  mabp <- ((m1+m2+m3) /(b1+b2+b3))+  plot_annotation(
    title = paste('[',crypto[x],']',
                  'binance exchange vs max exchange'))
  print(mabp)
})
```

```{r}

```

