---
title: "tradehistory"
author: "kidneyweakx"
date: "`r Sys.time()`"
output:
  html_document:
    highlight: pygments
    theme: flatly
    css: ../style.css
---

### API & Package Setting
```{r setup, include=FALSE}
rm(list=ls(all=T))
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, tidyquant,reticulate)
# reticulate
use_condaenv("cloud",conda = "D:\\app\\Anaconda3\\condabin\\conda")
max <- import("max.client")
client <- max$Client(Sys.getenv("MAX_API_KEY"),
                     Sys.getenv("MAX_API_SECRET"))
```

### Python list to data.frame
```{r}
r2df <- function(l) {
  if(length(l)!=0){
    df <- data.frame(matrix(unlist(l), nrow=length(l), byrow=T),
                     stringsAsFactors=FALSE);
    name <- names(l[[1]]);colnames(df) <- name[1:ncol(df)];
    return(df)} }
```

### Get market & trade history
```{r}
m <- client$get_public_all_markets() %>% r2df
m <- m %>% filter(quote_unit=="usdt");get <- 0
trhis <- do.call(rbind,lapply(c(1:nrow(m)), function(i){ 
  client$get_private_trade_history(m$id[i]) %>% r2df }))
colnames(trhis) <- c('id','price','volume','funds','market',
                     'market_name','created_at','created_at_in_ms',
                     'side','fee','fee_currency','order_id','info',
                     'vol','fee_currency','oid')
tr <- trhis %>% select(price, volume, market, created_at,side) %>% 
  mutate(date = as_datetime(as.numeric(created_at)),
        usdtprice = as.numeric(price)*as.numeric(volume)) 
```